# Riddler Classic
### From here: 
##### https://fivethirtyeight.com/features/beware-the-hot-pumpkin/

Note that 61 players are playing this game, that the first person to hold the pumpkin counts "1", and that the person to count the fixed number $N$ is eliminated. Each player to be eliminated is thus positioned such that the number $N$ is equal to some multiple of however many players remain, plus their own number position. 

Thus, each constraint of some player positioned as player number $m$ generates an infinite list of possibilities for what $N$ could be; if the first players were eliminated right away, the possibilities would begin 1, 62, 123, etc. We are asked to find the lowest number that intersects all the possible ranges, given our constraints. 

Taking a preliminary run at it, we see the first several such numbers that are off by fixed constants from multiples of 61, 60, etc:  

In [2]:
for i in range(15):
    print(18 + 61*(i+1))

79
140
201
262
323
384
445
506
567
628
689
750
811
872
933


In [3]:
for i in range(15):
    print(32 + 60*(i+1))

92
152
212
272
332
392
452
512
572
632
692
752
812
872
932


In [4]:
for i in range(15):
    print(59*(i+1))

59
118
177
236
295
354
413
472
531
590
649
708
767
826
885


Finding no overlap, we compute more intensely: 

In [5]:
first = [ 19+61*i for i in range(10000) ]
second = [ 32+60*i for i in range(10000) ]
third = [ 1+59*i for i in range(10000) ]

In [6]:
first_set = set(first)
firstinter = first_set.intersection(second)

In [8]:
print(firstinter.intersection(third))

{136232, 568112, 352172}


So the minimum possible $N$ is 136,232. Wow. 

# Extra Credit: 

Suppose the players were numbered from 1 to 61, with you as Player No. 1, the player to your left as Player No. 2 and so on. Which player won the game?

Note that we have to <i>assume</i> a particular value of $N$ here. In other words, in the above problem, we were given some information on how the game went, and then asked "What was the smallest value of $N$ the group could have used for this game?" The question implies that said smallest value is not necessarily what was used--and, moreover, whether 136,232 was in fact used (instead of, say, 568,112) could have an impact on the winner. So then, we proceed with $N = 136232.$

In [58]:
#We consider our players as numbered elements in a list
theplayers = [i for i in range(0, 61)]
print(theplayers)
print(len(theplayers))

#What is our value of N?
N = 136232

#We think in terms of elminating all the players but 1
theelims = len(theplayers)-1
spottracker = 0
while len(theplayers) > 1:
    #This operation represents the remainder after appropriate division
    unlucky = N % len(theplayers)
    #Fence post error alert; 
    #Our players begin with number 0, so . . .
    unlucky -= 1
    #But where did we begin counting last time?
    unlucky += spottracker
    #And in case we're now out of range: 
    unlucky = unlucky % len(theplayers)
    #Also, for next time: 
    spottracker = unlucky
    #For extra visibility: 
    #print(theplayers)
    
    #And these players get deleted: 
    del theplayers[unlucky]

#And when it's all over, the winner: 
print("The winner is: ", theplayers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]
61
The winner is:  [57]


In [59]:
#Is it different with a different valid, but larger, N?

#We consider our players as numbered elements in a list
theplayers = [i for i in range(0, 61)]
print(theplayers)
print(len(theplayers))

#What is our value of N?
N = 568112

#We think in terms of elminating all the players but 1
theelims = len(theplayers)-1
spottracker = 0
while len(theplayers) > 1:
    #This operation represents the remainder after appropriate division
    unlucky = N % len(theplayers)
    #Fence post error alert; 
    #Our players begin with number 0, so . . .
    unlucky -= 1
    #But where did we begin counting last time?
    unlucky += spottracker
    #And in case we're now out of range: 
    unlucky = unlucky % len(theplayers)
    #Also, for next time: 
    spottracker = unlucky
    #For extra visibility: 
    #print(theplayers)
    
    #And these players get deleted: 
    del theplayers[unlucky]

#And when it's all over, the winner: 
print("The winner is: ", theplayers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]
61
The winner is:  [21]


In [60]:
#How about this one?

#We consider our players as numbered elements in a list
theplayers = [i for i in range(0, 61)]
print(theplayers)
print(len(theplayers))

#What is our value of N?
N = 352172

#We think in terms of elminating all the players but 1
theelims = len(theplayers)-1
spottracker = 0
while len(theplayers) > 1:
    #This operation represents the remainder after appropriate division
    unlucky = N % len(theplayers)
    #Fence post error alert; 
    #Our players begin with number 0, so . . .
    unlucky -= 1
    #But where did we begin counting last time?
    unlucky += spottracker
    #And in case we're now out of range: 
    unlucky = unlucky % len(theplayers)
    #Also, for next time: 
    spottracker = unlucky
    #For extra visibility: 
    #print(theplayers)
    
    #And these players get deleted: 
    del theplayers[unlucky]

#And when it's all over, the winner: 
print("The winner is: ", theplayers)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]
61
The winner is:  [16]


Indeed it is!

# Extra Extra Credit: 

The smallest value of $N$ that would make us, in position 0, the winner.

In [61]:
#Setting a sensible starting candidate for N: 
N = 2

victory = 0
#We think in terms of elminating all the players but 1
while victory == 0:
    theplayers = [i for i in range(0, 61)]
    theelims = len(theplayers)-1
    spottracker = 0
    while len(theplayers) > 1:
        #This operation represents the remainder after appropriate division
        unlucky = N % len(theplayers)
        #Fence post error alert; 
        #Our players begin with number 0, so . . .
        unlucky -= 1
        #But where did we begin counting last time?
        unlucky += spottracker
        #And in case we're now out of range: 
        unlucky = unlucky % len(theplayers)
        #Also, for next time: 
        spottracker = unlucky
        #And these players get deleted: 
        del theplayers[unlucky]
    #Sanity check printing: 
    #print(N)
    
    if theplayers == [1]:
        victory = 1
    else:
        N += 1

#And when it's all over, the winner: 
print("The smallest winning value of N is: ", N)

2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
The smallest winning value of N is:  72
